#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hi', 'HelloSayer']

#Cell
def say_hi(to):
    "Say hi to someone"
    return f'Hello {to} :)'

say_hi('nbdev')

#Cell
class HelloSayer:
    "say hello to `to` using `say_hi` func"

    def __init__(self, to):
        self.to = to

    def say(self):
        "do the saying"
        return say_hi(self.to)